# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/sofiar/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/sofiar

PRODUCT_COPY_FILES += \
    vendor/motorola/sofiar/proprietary/product/framework/vendor.qti.hardware.fingerprint-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.fingerprint-V1.0-java.jar \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoft_calibverify_TriCamera.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoft_calibverify_TriCamera.so \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoft_tricam_calibration.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoft_tricam_calibration.so \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoft_tricam_verification.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoft_tricam_verification.so \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoftbase.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoftbase.so \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoftcalibration_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoftcalibration_jni.so \
    vendor/motorola/sofiar/proprietary/product/lib64/libarcsoftverification_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libarcsoftverification_jni.so \
    vendor/motorola/sofiar/proprietary/vendor/bin/capsense_reset:$(TARGET_COPY_OUT_VENDOR)/bin/capsense_reset \
    vendor/motorola/sofiar/proprietary/vendor/bin/charge_only_mode:$(TARGET_COPY_OUT_VENDOR)/bin/charge_only_mode \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/arcsoft_calibration_u_dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/arcsoft_calibration_u_dc.bin \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/cameraconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cameraconfig.txt \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/dual_golden.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dual_golden.bin \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/mot_ov02a_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_ov02a_chromatix.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/mot_ov16a1q_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_ov16a1q_chromatix.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/mot_ov16e10_sofiarow_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_ov16e10_sofiarow_chromatix.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/mot_ov8856_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_ov8856_chromatix.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/camera/mot_s5k4h7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_s5k4h7_chromatix.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/1kHz_Audio_Mono.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/1kHz_Audio_Mono.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/1kR1_5kL7s.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/1kR1_5kL7s.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/2kHz_Audio_Mono.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/2kHz_Audio_Mono.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/2kHz_Mono_1s.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/2kHz_Mono_1s.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/PinkNoise_m19db_RmsPow.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/PinkNoise_m19db_RmsPow.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/Silence.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/Silence.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/audio_cal.wav:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/audio_cal.wav \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/batch/DCPDetection.bat:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/batch/DCPDetection.bat \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/batch/DCPDetectionReadFile.bat:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/batch/DCPDetectionReadFile.bat \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/calib_tas25xx.config:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/calib_tas25xx.config \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_alt_cfg:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_alt_cfg \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_cfg:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_cfg \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_cfg_lda:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_cfg_lda \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_cfg_model_assembly:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_cfg_model_assembly \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_cfg_model_mmi:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_cfg_model_mmi \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_mmi_mode_order:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_mmi_mode_order \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_pat_mode_order:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_pat_mode_order \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/cqatest_sequence_mode_order:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/cqatest_sequence_mode_order \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/focaltech-tm_ft8756_fhd_vid-ft8756-sofiar.ini:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/focaltech-tm_ft8756_fhd_vid-ft8756-sofiar.ini \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/key_code_map.txt:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/key_code_map.txt \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/12m/tcmd_leds.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/12m/tcmd_leds.cfg \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_FE12MB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_FE12MB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_QE13MB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_QE13MB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_RC14MB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_RC14MB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_RC1BMB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_RC1BMB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_RE1BMB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_RE1BMB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_RX14MB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_RX14MB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/motorola/firmware/emmc_ffu_15_RX1BMB.fw:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/firmware/emmc_ffu_15_RX1BMB.fw \
    vendor/motorola/sofiar/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_auo_1080p_636.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_auo_1080p_636.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_636.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_636.xml \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/ak991x_polling_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_polling_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/default_sensors.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/dps368_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/dps368_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/icp101xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icp101xx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6ds3_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6ds3_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dsm_0_16g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0_16g.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dsm_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0_8g.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dso_0_16g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0_16g.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/lsm6dso_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0_8g.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/ltr2568_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ltr2568_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/ltr308_0_on_change.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ltr308_0_on_change.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mmc5603x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mmc5603x_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mn29xxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mn29xxx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mn59xxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mn59xxx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mot_chopchop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_chopchop.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mot_devorient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_devorient.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/mot_ltv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_ltv.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_ak991x_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_icm4x6xx_0-i3c.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_icm4x6xx_0-i3c.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_lsm6dso_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_mmc5603x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_mmc5603x_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_mn29xxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_mn29xxx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/nicobar_mn59xxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_mn59xxx_0.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd2725.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/tmd2750.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd2750.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmx4903.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/config/tsl2540.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tsl2540.json \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/motorola/sofiar/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/motorola/sofiar/proprietary/vendor/etc/thermal-engine-sofiar.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-sofiar.conf \
    vendor/motorola/sofiar/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/sofiar/proprietary/vendor/firmware/FT8006U_Pramboot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8006U_Pramboot.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/focaltech-ft8756-0d-01-sofiar.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ft8756-0d-01-sofiar.bin \
    vendor/motorola/sofiar/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/motorola/sofiar/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/motorola/sofiar/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/motorola/sofiar/proprietary/vendor/lib/hw/sound_trigger.primary.trinket.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sound_trigger.primary.trinket.so \
    vendor/motorola/sofiar/proprietary/vendor/lib/libadspd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadspd.so \
    vendor/motorola/sofiar/proprietary/vendor/lib/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.ssc.so \
    vendor/motorola/sofiar/proprietary/vendor/lib64/hw/sound_trigger.primary.trinket.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sound_trigger.primary.trinket.so \
    vendor/motorola/sofiar/proprietary/vendor/lib64/libadspd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadspd.so \
    vendor/motorola/sofiar/proprietary/vendor/lib64/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmpbase.so \
    vendor/motorola/sofiar/proprietary/vendor/lib64/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.ssc.so \
    vendor/motorola/sofiar/proprietary/vendor/lib64/vndk/libtinyalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vndk/libtinyalsa.so

PRODUCT_PACKAGES += \
